name: pr
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  VERSION: '0.0.1'

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew installDist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/install
          retention-days: 1
  build-docker:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: build/install

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/avisi-cloud/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.VERSION }}
  publish-example-site:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: build/install

      - name: Generate example site
        run: |
          sudo apt-get install -y graphviz
          chmod +x build/install/structurizr-site-generatr/bin/structurizr-site-generatr
          build/install/structurizr-site-generatr/bin/structurizr-site-generatr generate-site --git-url "https://github.com/avisi-cloud/structurizr-site-generatr.git" --workspace-file docs/example/workspace.dsl --branches generate-publish-example-workspace

      - name: Publish example site
        uses: peaceiris/actions-gh-pages@v3
        #        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
